resource_group_name = "aca-demo-rg"
project_name        = "acadocker"
container_app_name  = "my-container-app"
dockerhub_username  = "ramakrishna1359"
image_name          = "Azure_container"
location            = "eastus"
